# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravaAuth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='key',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
