# Generated by Django 2.0.1 on 2018-01-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='text',
            new_name='value',
        ),
    ]
