# Generated by Django 2.0.1 on 2018-01-23 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='keys.User'),
        ),
    ]
