# Generated by Django 2.0.1 on 2018-01-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0005_auto_20180123_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
