# Generated by Django 2.0.1 on 2018-05-15 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0006_auto_20180123_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='value',
        ),
        migrations.AddField(
            model_name='key',
            name='token',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='key',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
