# Generated by Django 2.0.1 on 2018-05-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0007_auto_20180515_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='strava_id',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
