# Generated by Django 2.0.1 on 2018-08-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0008_key_strava_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='service',
            field=models.CharField(choices=[('ST', 'Strava')], default=None, max_length=2),
        ),
    ]
