# Generated by Django 2.0.1 on 2018-08-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0009_key_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='refresh_token',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='key',
            name='service',
            field=models.CharField(choices=[('STR', 'Strava'), ('SPO', 'Spotify')], default=None, max_length=3),
        ),
    ]
