# Generated by Django 2.0.1 on 2018-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0010_auto_20180828_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='refresh_token',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='key',
            name='strava_id',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
